name: Ejemplo de flujo de trabajo

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: npm install

      - name: Crear paquete
        run: npm run build
